[build]
command = "npm --prefix ./netlify install && npm --prefix ./frontend run build"
publish = "frontend/build"
environment = { NODE_VERSION = "18" }


[dev]
  functions = "netlify/functions"  # Functions directory during local dev
  publish = "public"               # Optional for static assets
